apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gymbro
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - bot/pvc.yaml
  - bot/deployment.yaml
  - web/deployment.yaml
  - web/service.yaml
  - ingress.yaml
images:
- name: ghcr.io/chivta/gymbro/api
  newTag: placeholder
- name: ghcr.io/chivta/gymbro/bot
  newTag: placeholder
- name: ghcr.io/chivta/gymbro/web
  newTag: placeholder
