apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GP0k/aUAq4IIH9xIB+B9Y5Ibea7EjBFp3cuRkLYDDmxU+SfgJfS5Ua4fJG73yce2094oi86McwW6YlSLtW1Mwa8ZsZ8=,iv:fzWyHgxONOcxH/uou1oAvZ0BkAFkjQB5KaMH+nDHQoI=,tag:Kh8CSCklI0ovvqrdEu6lfQ==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:ZQKkAog2/MpS9Q2ufR/h1rSVou0iGNOvGQYUKqOzDK9tzuQKgVCEPdogNPab3A==,iv:H47Q61lh4ewYwxa/y9w0TDMBeqLISuqiS5dQeBZH1dE=,tag:JiHWRdJ5kmhhS4ehDTnCyw==,type:str]
    #ENC[AES256_GCM,data:/reaYnJs5Wzk+6VEUfFxXXvWH5FBwNHT4AQb+7Utd/Srog18oe2TTu8MBPdGHpG+57MeqCTxcBYOyUk7T7H9nmG8myoV7HoIW/kG7vyi7g==,iv:9XxcLdhk2pUTkb+KGpgGfJhpkRWZNUF1MWbzU58LaPg=,tag:snyTGAfADupj/ffIfIup7w==,type:comment]
    API_SECRET: ENC[AES256_GCM,data:lOruzOZ1LnWxyh4DCFHTzvhJCAG7iFopKvBHMv/K1iKOpVmKvMML6fWEM2t780AQWZyj1tWoQ41d+5gNx4q7rg==,iv:6ZhQLDw3u/CsGKYruUYXxKXfGYvi53VPfblRxsfc2w8=,tag:QUkmVcSx5c3ndpqxmNDV/w==,type:str]
    #ENC[AES256_GCM,data:o22b8je5unHTl4lGqx3QwQW1QuQP136Zs2Bpsyak2tz53BnRFecEV3+Ane1nEMq7aLVqvCg8fYvwB3QKLdRzqjMf,iv:VxtHbQ+sAexO7l3y+HO4iCuI2pGtDL6BrYRroqlKgpM=,tag:aIRC+9csAm1/jkzEeiTTcA==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:m7N7x6rB,iv:dv3otbI3EUF5/EFF/9wqwt6wB0dWe38TaQ9BKETxipY=,tag:sGPP9meGflMnF4Py28qy1w==,type:str]
    #ENC[AES256_GCM,data:A0TIjxBoysjaM/sG5BAcjSz4FtB0OBcL6aCPilLFfBby7KtjnA==,iv:K6TwXUgavYaL1MfyOgLNnBbdOPVZbuTYWBcQI3soTUU=,tag:uylSQad4O9b2ETSV8FBZDA==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NMIdYRWSTdQqOUxvdFYNhk6cOC2/Xov2BfuXRO96mD4JYN5TFWVEgxe1jqmC4gol,iv:UA9SYf1uDKs2jk/h+a+jYWQq6IePNeAAsdBhqoVH/tI=,tag:FUfUDOL4+/Ee3kEoCUdpMg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:B0KPTEkF,iv:hgTRok3OVOFdIcc/z41mk4SbjSEgBROcVSiObUcZQys=,tag:qHmFWE29mbpDOP/ee/p+kg==,type:str]
    #ENC[AES256_GCM,data:YYWbh7i6Y+/vw0z3tR9tXT/p8GGglJerG/e2rmoQ1ZkTzMiHfLwizcfRTZx+BXTnJkKnKQ7Jcxrjt6wNigU=,iv:F8OoBtuhTBAZzmuuhsBFdc9DDzlq7yLrXrxYwGpQMFA=,tag://K/GoQlxLwWlL1eB7avYA==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:9+QQkV8ex8r1bz0R++yGXmhlE5dcRCgeMrEvgEWaypFiLSo5oTSg6fakF6QKXwqIyK1rummWZE/3yRQxL8Ychq7fdKorZbyAhTZLhj8fn6wgwy+IA+toD6Kn+w3I/3kcqXEsvMJTbw==,iv:pgr+UuzEY2O6v8fl8PXEyODVHeuG2gSzhKbESx8bLTc=,tag:Y17qOtMt1cEWdbKIo0Cxew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUFQ4ak5EQW9kZDJ1Y0Y2
            TGt3NFRxSFc2bXNIeGxubFlWSlJWMWc3QngwCnY5YndkRkwvWlkyMUtSVjBXUDEw
            QjVLcUd2UFA0dHZoSmxtVFo5YzF3bUEKLS0tIEU4VEJrbUthb3VJc0dTSlZzem9L
            VGc4UzhOREkwZGdta3lsWVZEL2FUV0UKMlYQ7PhpNR6rhgusetpoJlrR5oeT3Wz3
            N1lnin9t2zasWadgI97ergQ6KbV2y/1V8jESfA/xZq1/9rQi/XkotA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T09:42:44Z"
    mac: ENC[AES256_GCM,data:7JDOivf1CP3kXI3MZ3G6q5mgzMKcttM/x/5ncp9Gn190S5LEQH7HJvV/FETk2Dj7J6Zdit/0wCZyNcGAtfQsjtQa6F5nSFNRmYa3HH55Ha7U652otiz317ItOne1a996Ou3AYIU1S11HivPZCXOUKKBhS/rKPOIZElngFaJ8kAc=,iv:eGFSm3mco8rsRFUjb9FLElnZQFwJ2hGJQo52+peSoog=,tag:86/sHr6gXqcWmV+Yuda8lA==,type:str]
    version: 3.13.3
