apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:w67Y4kfuLS8OZg78Vl3xSGcuw6BqmSuO9mNFRFztaAJBmrW0jSwcPbgXrh7iJQpRw5dHqItE2l16HW9eHFXB+oaZPskYBfU=,iv:0IJr7FAmlsKE6nEJNqoYoYxtIaWJReQ/o5tftr7LV/s=,tag:sPGqDb7rqAOgrXOuGB3d0w==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:41nOFo+W2dxjYkjbfBeTA54r1RdlkKImX6kLFy/kUtq9aqXbFvzfZnh84BwUEw==,iv:1fbTuhukF2Vru622WOLSNaw2sPHT3Ah9VLxm03HnfzI=,tag:pqJhZDqf/glPyPzMshxtow==,type:str]
    #ENC[AES256_GCM,data:hRTlFI/141OdvDOoDnw7Xov7ScH+ICdcuJZ1Gi+aRm+JfDKu9YcYQCsG6g1IC2jUO+A4U063Up+Zf1HgP2xE1CNG8V79NQ/QgSVbU2HiIQ==,iv:PXE089HlPF6tt7eXW5XAUHslUp3kmMZLlvsTn2HyMts=,tag:g/uF57wGyHUYvSU4ceXn0Q==,type:comment]
    API_SECRET: ENC[AES256_GCM,data:GteBRZAU7It7sGVJK7oAmjbm30gKTCqjDXwUIk6Di7nYqPzlUSlhV/W9QRTlpVDxm1KD3cvBXTxMfbqTmukHdQ==,iv:d+vFr08rslQOgn4zWnDruwumoknM8YuIweko4LgORvo=,tag:y6EyCZzNnFwXG8FSUoaXiQ==,type:str]
    #ENC[AES256_GCM,data:IBWmSkAT5MpJ+LpUQmWjnEMl02UOfLSrYds/sM+0AiusdcVoO9JJXV/UQKwaY/fvPU+MTiTKmoWL9s16s4XbgS5B,iv:NekvF7Wpgmd6p1iwykI66DQp4BeK7Y1cON3fBOMEWAI=,tag:lWx2WaD5ZiKxqr0vF44E2A==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:ZSsYkWL7,iv:UewmwWRPKw2xWLJ0D2r+MoFcJFlm1Zj/m8J6pTC/Z5o=,tag:6+CmSuG1dZMt4Og/KRp1Yw==,type:str]
    #ENC[AES256_GCM,data:FjLjO5zZcVl/C3EgStlEOq34QQsGW0PrXg+z0vxDwaIBbBDyuw==,iv:Khqb/pMXmQrDy86b/LYriCgad1Vj4kG+2LQyX/WgUFw=,tag:Pj07Ll6YAdc3YTm4xeaizw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8D7k+oaQG/wAQT0XUsEaAOA+6QvLEI0qFgI0TZk3lqeMUwau73VtpWvQqKrwOoSV,iv:qzqH9h0HxQewBbw6NPmlnRW2oLbGY64BNjmqrcJ8jBY=,tag:GC1ymCm/tdQUW+mdoojj0A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:QAUmxLRc,iv:osL5ia6i/tZE1dNSrgEpfAvf2PgcylwGPLCGL5HLuY4=,tag:LsIHfjX4N5VXh42SPPyfGw==,type:str]
    #ENC[AES256_GCM,data:gSsTZJXMopmqapEZmoktv1bVnRjv450n1R4ik54sc9CQRYevbfv+KVsEhgOGc0TnjtE8U+dtI51SaJU362c=,iv:5ceNLbYFtI/8YD1EFsIrYImEytl+JEFLAwKNJca22UU=,tag:YnTmm0P0wChbILllMLkS2Q==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:BzJMFLohwCfWOoelHcBZztFDqYIKmuDJXbLLp/ItMyBzYk5BXaGKuZcuwSe7u7eW4no1gT8nwk5KYEJjRDdq/Ea3xowVTIuygxzLbLDJIGvn3Kp7Wi8kkQvZGTqJqk4C+XxzOdgwIA==,iv:KKoX5uNdwyn94T6ZRdUa6CD3mx0vyl6hJy/9MQ+OUig=,tag:0yfRl5T/8QcjQUVD8+GmmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY09nbFZPNnM1bVJWMGF6
            SHlEMTFVMitySU4yaWxmOFdScVMxc1VDcWlvClkwTlltZWtvai84V3FtUjl6Qm1s
            L3Z2S2k0a1FDZ1pENStyNVMxUmxiUXcKLS0tIFRrK2l2bDNFb01xWitNMVhoQUxC
            YlpwTk5mZUdHaU5CRUNhNkxraU5kVmMKR3nhhNnNaURAz8NYRpcZggImEDAA2Zon
            SyqvqmvicAA8xa/S7WLbeznYfPllSuo0mg4eJnUN5/DubF6Kx0KuSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T17:20:35Z"
    mac: ENC[AES256_GCM,data:BQjyZmu1Y+TBHBhVVgEj5Vkyc6FLRCw66mf0mcdgioJEKewch303xEy0Y3dpVEl/C3Sq6uaEeQXvgEnex91owKuDSx8U/jY7ns5d+Hg9gKOA9ZA71VU/RZi8t7YLTYZxU8jiAj33lBBl2NajdVaBRrHf6CfMCqXO+GkCyXjnQp0=,iv:eto8YlIPR3Dbo+ZZaxz6PyHwoeZB7gxZUgmFGRdsVEg=,tag:mzL7b6e3yNLZR1AnWKncJw==,type:str]
    version: 3.13.3
